const PERSONS = [
	{
		id: "1",
		email: "1@mail.com",
		firstName: "First",
		lastName: "Person",
	},
	{
		id: "2",
		email: "2@mail.com",
		firstName: "Second",
		lastName: "Person",
	},
	{
		id: "3",
		email: "3@mail.com",
		firstName: "Third",
		lastName: "Person",
	},
	{
		id: "4",
		email: "4@mail.com",
		firstName: "Fourth",
		lastName: "Person",
	},
	{
		id: "5",
		email: "5@mail.com",
		firstName: "Fifth",
		lastName: "Person",
	},
	{
		id: "6",
		email: "6@mail.com",
		firstName: "Sixth",
		lastName: "Person",
	},
	{
		id: "7",
		email: "7@mail.com",
		firstName: "Seventh",
		lastName: "Person",
	},
	{
		id: "8",
		email: "8@mail.com",
		firstName: "Eighth",
		lastName: "Person",
	},
	{
		id: "9",
		email: "9@mail.com",
		firstName: "Ninth",
		lastName: "Person",
	},
	{
		id: "10",
		email: "10@mail.com",
		firstName: "Tenth",
		lastName: "Person",
	},
	{
		id: "11",
		email: "11@mail.com",
		firstName: "Eleventh",
		lastName: "Person",
	},
	{
		id: "12",
		email: "12@mail.com",
		firstName: "Twelfth ",
		lastName: "Person",
	},
	{
		id: "13",
		email: "13@mail.com",
		firstName: "Thirteenth",
		lastName: "Person",
	},
	{
		id: "14",
		email: "14@mail.com",
		firstName: "Fourteenth",
		lastName: "Person",
	},
	{
		id: "15",
		email: "15@mail.com",
		firstName: "Fifteenth",
		lastName: "Person",
	},
	{
		id: "16",
		email: "16@mail.com",
		firstName: "Sixteenth",
		lastName: "Person",
	},
	{
		id: "17",
		email: "17@mail.com",
		firstName: "Seventeenth",
		lastName: "Person",
	},
	{
		id: "18",
		email: "18@mail.com",
		firstName: "Eighteenth",
		lastName: "Person",
	},
	{
		id: "19",
		email: "19@mail.com",
		firstName: "Nineteenth",
		lastName: "Person",
	},
	{
		id: "20",
		email: "20@mail.com",
		firstName: "Twentieth",
		lastName: "Person",
	},
	{
		id: "21",
		email: "21@mail.com",
		firstName: "Twenty-First",
		lastName: "Person",
	},
	{
		id: "22",
		email: "22@mail.com",
		firstName: "Twenty-Second",
		lastName: "Person",
	},
	{
		id: "23",
		email: "23@mail.com",
		firstName: "Twenty-Third",
		lastName: "Person",
	},
	{
		id: "24",
		email: "24@mail.com",
		firstName: "Twenty-Fourth",
		lastName: "Person",
	},
	{
		id: "25",
		email: "25@mail.com",
		firstName: "Twenty-Fifth",
		lastName: "Person",
	},
	{
		id: "26",
		email: "26@mail.com",
		firstName: "Twenty-Sixth",
		lastName: "Person",
	},
	{
		id: "27",
		email: "27@mail.com",
		firstName: "Twenty-Seventh",
		lastName: "Person",
	},
	{
		id: "28",
		email: "28@mail.com",
		firstName: "Twenty-Eighth",
		lastName: "Person",
	},
	{
		id: "29",
		email: "29@mail.com",
		firstName: "Twenty-Ninth",
		lastName: "Person",
	},
	{
		id: "30",
		email: "30@mail.com",
		firstName: "Thirtieth",
		lastName: "Person",
	},
];

export default PERSONS;
